### ISSUE TITLE
Needs a 64x64 and 128x128 icon

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.tuxfamily.XMoto#1]
In order to show up on the [apps page](https://beta.flathub.org/apps) this needs at least a 64x64 icon. The largest icon this currently contains is 48px.

**Comment by nbenitez** [comment]
I just submitted a PR with several updates to xmoto package, one of them is the substitution of the low res png icon with a svg one.

**Comment by bbhtt** [comment]
Closing as it has a svg now
